<%@ Page Language="C#" AutoEventWireup="true" CodeFile="DesGroup.aspx.cs" Inherits="_Default" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>分组</title>
</head>
<body background="Image/背景（长） - 副本2.0.png">
    <form id="form1" runat="server">
    <center>
    <asp:Label ID="lblManager" runat="server" Text="分   组   表" 
            style="font-size: xx-large; font-family: 黑体"></asp:Label>

    &nbsp;&nbsp;<br />
       
        <br />
        &nbsp;&nbsp;&nbsp;&nbsp;<br />
         <asp:TextBox ID="txtkong" runat="server" Width="0px" Height="0px" 
           style="background-color: #FFCCFF"></asp:TextBox>
         <asp:TextBox ID="txtSummaryScore" runat="server" Width="0px" Height="0px" 
                style="background-color: #FFCCFF"></asp:TextBox>
           <asp:TextBox ID="txtScoreStudent" runat="server" Width="0px" Height="0px" 
                style="background-color: #FFCCFF"></asp:TextBox>
           <asp:TextBox ID="txtScoreTeacher" runat="server" Width="0px" Height="0px" 
                style="background-color: #FFCCFF"></asp:TextBox>
&nbsp;<asp:Button ID="btncalculate" runat="server" Text="计算成绩" 
            onclick="btncalculate_Click" 
            
            style="font-size: x-large; font-weight: 700; font-family: 黑体; color: #FFFFFF; background-color: #FF0000" 
            Height="41px" />
 &nbsp;&nbsp;
        <asp:Button ID="butCreat" runat="server" Height="34px" Text="新增" 
        Width="114px" style="font-size: large; font-weight: 700; background-color: #CCCCCC;" 
        onclick="butCreat_Click" />

      &nbsp;&nbsp;<asp:Label ID="lblCreatDID" runat="server" Text="组号" 
        style="font-size: large; color: #FF6699; font-weight: 700"></asp:Label>
    <asp:TextBox ID="txtCreatDID" runat="server" Height="22px"></asp:TextBox>
     &nbsp; &nbsp;<asp:Label ID="lblCreatProject" runat="server" Text="项目名称" 
        style="font-size: large; color: #FF6699; font-weight: 700"></asp:Label>
&nbsp;<asp:TextBox ID="txtCreatProject" runat="server" Height="23px"></asp:TextBox>
         &nbsp; 
        <asp:Button ID="btnjump" runat="server" Text="查看评分数量" Height="35px" 
            onclick="btnjump_Click" style="font-size: large; font-weight: 700; background-color: #CCCCCC;" 
            Width="123px" />
        &nbsp; 
        <asp:Button ID="btnChangeIndex" runat="server" Height="36px" Text="更改指标" 
        Width="115px" 
        style="font-size: large; font-weight: 700; background-color: #CCCCCC" 
        onclick="btnChangeIndex_Click" />
          &nbsp; 
        <asp:Button ID="btnreturn" runat="server" Text="退出" onclick="btnreturn_Click" 
            style="font-weight: 700; font-size: large; background-color: #CCCCCC" 
            Height="37px" Width="115px" />
         </center>
    <br />
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
     <br />
     <br />
     &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;<asp:Label 
        ID="lblfinal" runat="server" 
        Text="注:结束请新增'0'和'评分结束'" 
        
        
        style="font-weight: 700; color: #FF3399; background-color: #FFFFFF; font-size: x-large;"></asp:Label> 
       
    &nbsp;&nbsp; 
       
    <br />
    <center>
        <br />
    <br />
    <asp:GridView ID="GVAdmin" runat="server" AllowPaging="True" 
            AutoGenerateColumns="False" Height="342px" 
            onselectedindexchanged="GridView1_SelectedIndexChanged" Width="555px" 
            CellPadding="4" ForeColor="#333333" GridLines="None" 
            AutoGenerateDeleteButton="True" AutoGenerateEditButton="True">
            <AlternatingRowStyle BackColor="White" ForeColor="#284775" />
            <Columns>
            <asp:BoundField DataField="DID" HeaderText="组号"  />
             <asp:BoundField DataField="Project" HeaderText="项目名称"  />
             <asp:TemplateField  HeaderText="结果">
               <ItemTemplate>
                <a href='Summary.aspx?id=<%#DataBinder.Eval(Container, "DataItem.DID").ToString()%>'>查询结果</a> 
               </ItemTemplate>
             </asp:TemplateField>
            </Columns>
            <EditRowStyle BackColor="#999999" />
            <FooterStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
            <HeaderStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
            <PagerStyle BackColor="#284775" ForeColor="White" HorizontalAlign="Center" />
            <RowStyle BackColor="#F7F6F3" ForeColor="#333333" />
            <SelectedRowStyle BackColor="#E2DED6" Font-Bold="True" ForeColor="#333333" />
            <SortedAscendingCellStyle BackColor="#E9E7E2" />
            <SortedAscendingHeaderStyle BackColor="#506C8C" />
            <SortedDescendingCellStyle BackColor="#FFFDF8" />
            <SortedDescendingHeaderStyle BackColor="#6F8DAE" />
        </asp:GridView>
        <br />
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        </center>
    </form>
</body>
</html>
